# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 768425d77319790c4261d695440bb9052520f294560b9e1390b0565cbb495b0f2fc42b16c2bf8e75776c6eb7f5253e718bb4681d21b2ba49b5b885f4a3545ca9

test:
  secret_key_base: f2e37de171a9aa8db4eac0ab2cf7a57f83a26229148dcb53eebb229d39b95008bd1091f3955ea197ce1c86afc7a2651eae518583d8baf64dfdb011c9c92e6491

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
